Supports combinations of `--show-column-numbers`, `--hide-error-codes` and `--show-error-end`.
Sample string for test:

```plain
main.py:1: error: Unsupported operand types for - ("int" and "str")  [operator]
main.py:1: note: See 'https://mypy.rtfd.io/en/stable/_refs.html#code-operator' for more info
main.py:1:2:3:4: error: Unsupported operand types for - ("int" and "str")  [operator]
main.py:1:2:3:4: note: See 'https://mypy.rtfd.io/en/stable/_refs.html#code-operator' for more info
main.py:1:2: error: Unsupported operand types for - ("int" and "str")  [operator]
main.py:1:2: note: See 'https://mypy.rtfd.io/en/stable/_refs.html#code-operator' for more info
```

Expect:
- line=1 (×2 lines)
- line=1,column=2,endLine=3,endColumn=4 (×2 lines)
- line=1,column=2 (×2 lines)